config/routes.rb
Rails.application.routes.draw do
    resources :bus_stops do
        resources :time_tables do
            collection { post :import }
        end
        collection { post :import }
    end

end

app/models/bus_stop.rb
# -*- coding: utf-8 -*-

class BusStop < ActiveRecord::Base
    has_many :time_tables
    validates :name, uniqueness: {message: "重複しています"}, presence: {message: "入力してください"}

    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            # 一致するnameをもつレコードを探す。なければ新規作成
            bus_stop = find_by(name: row["name"]) || new
            # CSVからデータを取得、設定する
            bus_stop.attributes = row.to_hash.slice(*updatable_attributes)
            # レコードを保存
            bus_stop.save
        end
    end

    def self.updatable_attributes
        ["name"]
    end
end

app/models/time_table.rb
# -*- coding: utf-8 -*-

class TimeTable < ActiveRecord::Base
    belongs_to :bus_stop
    validates :routes, uniqueness: {message: "重複しています"}, presence: {message: "入力してください"}

    def self.import(file, bus_stop_id)
        CSV.foreach(file.path, headers: true) do |row|
            # 一致するroutesをもつレコードを探す。なければ新規作成
            time_table = find_by(routes: row["routes"], bus_stop_id: bus_stop_id) || new
            # CSVからデータを取得、設定する
            row = row.to_hash
            row["bus_stop_id"] = bus_stop_id
            time_table.attributes = row.slice(*updatable_attributes)
            # レコードを保存
            p time_table
            time_table.save
        end
    end

    def self.updatable_attributes
        ["dow", "routes", "destination", "time", "bus_stop_id"]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bus_stops_controller.rb
# -*- coding: utf-8 -*-

class BusStopsController < ApplicationController
    def index
        @busStops = BusStop.all
    end

    def show
        @busStop = BusStop.find(params[:id])
    end

    def new
        @busStop = BusStop.new
    end

    def create
        @busStop = BusStop.new(busStop_params)
        if @busStop.save then
            redirect_to bus_stops_path
        else
            render 'new'
        end
    end

    def edit
        @busStop = BusStop.find(params[:id])
    end

    def update
        @busStop = BusStop.find(params[:id])
        if @busStop.update(busStop_params)
            redirect_to bus_stops_path
        else
            render 'edit'
        end
    end

    def destroy
        @busStop = BusStop.find(params[:id])
        @busStop.destroy
        redirect_to bus_stops_path
    end

    def import
        BusStop.import(params[:file])
        redirect_to bus_stops_path, notice: "CSVをインポートしました"
    end

private
    def busStop_params
        params[:bus_stop].permit(:name)
    end
end

app/controllers/time_tables_controller.rb
# -*- coding: utf-8 -*-

class TimeTablesController < ApplicationController
    def create
        @busStop = BusStop.find(params[:bus_stop_id])
        @timeTable = @busStop.time_tables.create(timeTable_params)
        redirect_to bus_stop_path(@busStop.id)
    end

    def destroy
        @timeTable = TimeTable.find(params[:id])
        @timeTable.destroy
        redirect_to bus_stop_path(params[:bus_stop_id])
    end

    def import
        TimeTable.import(params[:file], params[:bus_stop_id])
        redirect_to bus_stop_path(params[:bus_stop_id]), notice: "CSVをインポートしました"
    end

private
    def timeTable_params
        params[:time_table].permit(:dow, :routes, :destination, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bus_stops_helper.rb
module BusStopsHelper
end

app/helpers/time_tables_helper.rb
module TimeTablesHelper
end

app/views/bus_stops/edit.html.erb
<h1>Edit</h1>

<%= form_for @busStop do |b| %>
    <p>
    <%= b.label :name %>
    <%= b.text_field :name %>
    <% if @busStop.errors.any? %>
        <%= @busStop.errors.messages[:name][0] %>
    <% end %>
    </p>

    <p>
    <%= b.submit %>
    </p>
<% end %>

app/views/bus_stops/index.html.erb
<h1>BusStops</h1>

<ul>
    <% @busStops.each do |busStop| %>
        <li>
        <%= link_to busStop.name, bus_stop_path(busStop.id) %>
        <%= link_to "[Edit]", edit_bus_stop_path(busStop.id) %>
        <%= link_to "[DELETE]", bus_stop_path(busStop.id), method: :delete, data: {confirm: "are you sure?"} %>
        </li>
    <% end %>
</ul>

<%= link_to "Add New", new_bus_stop_path %>

<%= form_tag import_bus_stops_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "import" %>
<% end %>

app/views/bus_stops/new.html.erb
<h1>Add New</h1>

<%= form_for @busStop do |b| %>
    <p>
    <%= b.label :name %>
    <%= b.text_field :name %>
    <% if @busStop.errors.any? %>
        <%= @busStop.errors.messages[:name][0] %>
    <% end %>
    </p>

    <p>
    <%= b.submit %>
    </p>
<% end %>

app/views/bus_stops/show.html.erb
<h1><%= @busStop.name %></h1>

<ul>
    <% @busStop.time_tables.each do |timetable| %>
        <li>
            <%= timetable.dow %>
            <%= timetable.routes %>
            <%= timetable.destination %>
            <%= timetable.time %>
            <%= link_to "[Delete]", bus_stop_time_table_path(timetable.bus_stop_id, timetable.id), method: :delete, data: { confirm: "are you sure?" } %>
        </li>
    <% end %>
    <li>
</ul>
<ul>
        <%= form_for [@busStop, @busStop.time_tables.build] do |b| %>
            <%= b.label :dow %>
            <%= b.text_field :dow %>
            <%= b.label :routes %>
            <%= b.text_field :routes %>
            <%= b.label :destination %>
            <%= b.text_field :destination %>
            <%= b.label :time %>
            <%= b.text_field :time %>
            <%= b.submit %>
        <% end %>
    </li>
</ul>
<%= form_tag import_bus_stop_time_tables_path(@busStop.id), multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "import" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CampusBus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>